# Generated by Django 4.2.7 on 2025-10-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł sondażu')),
                ('description', models.TextField(verbose_name='Opis')),
                ('poll_type', models.CharField(choices=[('political', 'Polityczny'), ('social', 'Społeczny'), ('economic', 'Ekonomiczny'), ('other', 'Inny')], default='political', max_length=20, verbose_name='Typ sondażu')),
                ('options', models.JSONField(help_text='Lista opcji do wyboru', verbose_name='Opcje sondażu')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateTimeField(verbose_name='Data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyróżniony')),
                ('allow_multiple_votes', models.BooleanField(default=False, verbose_name='Pozwól na wielokrotne głosowanie')),
                ('require_authentication', models.BooleanField(default=True, verbose_name='Wymagaj uwierzytelnienia')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Łączna liczba głosów')),
                ('unique_voters', models.PositiveIntegerField(default=0, verbose_name='Unikalni głosujący')),
                ('tags', models.CharField(blank=True, help_text='Tagi oddzielone przecinkami', max_length=200, verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Sondaż',
                'verbose_name_plural': 'Sondaże',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Zatwierdzony')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentarz do sondażu',
                'verbose_name_plural': 'Komentarze do sondaży',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=100, verbose_name='Wybrana opcja')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fingerprint', models.CharField(blank=True, max_length=100, verbose_name='Fingerprint przeglądarki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Głos w sondażu',
                'verbose_name_plural': 'Głosy w sondażach',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'poll')},
            },
        ),
    ]
