# Generated by Django 4.2.7 on 2025-10-06 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numer projektu')),
                ('status', models.CharField(choices=[('draft', 'Projekt'), ('submitted', 'Złożony'), ('in_committee', 'W komisji'), ('first_reading', 'Pierwsze czytanie'), ('second_reading', 'Drugie czytanie'), ('third_reading', 'Trzecie czytanie'), ('passed', 'Przyjęty'), ('rejected', 'Odrzucony'), ('withdrawn', 'Wycofany')], default='draft', max_length=20, verbose_name='Status')),
                ('authors', models.TextField(help_text='Lista autorów projektu', verbose_name='Autorzy')),
                ('initiators', models.TextField(blank=True, help_text='Lista inicjatorów', verbose_name='Inicjatorzy')),
                ('submission_date', models.DateField(verbose_name='Data złożenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, verbose_name='Link do źródła')),
                ('document_url', models.URLField(blank=True, verbose_name='Link do dokumentu')),
                ('support_votes', models.PositiveIntegerField(default=0, verbose_name='Głosy za')),
                ('against_votes', models.PositiveIntegerField(default=0, verbose_name='Głosy przeciw')),
                ('neutral_votes', models.PositiveIntegerField(default=0, verbose_name='Głosy neutralne')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Łączna liczba głosów')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyróżniony')),
                ('tags', models.CharField(blank=True, help_text='Tagi oddzielone przecinkami', max_length=200, verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Projekt ustawy',
                'verbose_name_plural': 'Projekty ustaw',
                'ordering': ['-submission_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Projekt'), ('submitted', 'Złożony'), ('in_committee', 'W komisji'), ('first_reading', 'Pierwsze czytanie'), ('second_reading', 'Drugie czytanie'), ('third_reading', 'Trzecie czytanie'), ('passed', 'Przyjęty'), ('rejected', 'Odrzucony'), ('withdrawn', 'Wycofany')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Projekt'), ('submitted', 'Złożony'), ('in_committee', 'W komisji'), ('first_reading', 'Pierwsze czytanie'), ('second_reading', 'Drugie czytanie'), ('third_reading', 'Trzecie czytanie'), ('passed', 'Przyjęty'), ('rejected', 'Odrzucony'), ('withdrawn', 'Wycofany')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Opis zmiany')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='bills.bill')),
            ],
            options={
                'verbose_name': 'Aktualizacja projektu ustawy',
                'verbose_name_plural': 'Aktualizacje projektów ustaw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('support', 'Popieram'), ('against', 'Nie popieram'), ('neutral', 'Neutralny')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bills.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Głos na projekt ustawy',
                'verbose_name_plural': 'Głosy na projekty ustaw',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bill')},
            },
        ),
    ]
