# Generated by Django 4.2.7 on 2025-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='api_data',
            field=models.JSONField(blank=True, help_text='Dodatkowe dane z API', null=True, verbose_name='Dane API'),
        ),
        migrations.AddField(
            model_name='bill',
            name='data_source',
            field=models.CharField(choices=[('sejm_api', 'API Sejmu'), ('gov_pl', 'Gov.pl'), ('hybrid', 'Hybrydowe')], default='hybrid', max_length=20, verbose_name='Źródło danych'),
        ),
        migrations.AddField(
            model_name='bill',
            name='document_type',
            field=models.CharField(blank=True, help_text='Typ dokumentu z API Sejmu', max_length=50, verbose_name='Typ dokumentu'),
        ),
        migrations.AddField(
            model_name='bill',
            name='eli',
            field=models.URLField(blank=True, help_text='European Legislation Identifier', verbose_name='ELI'),
        ),
        migrations.AddField(
            model_name='bill',
            name='passed',
            field=models.BooleanField(default=False, help_text='Czy ustawa została uchwalona', verbose_name='Uchwalona'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sejm_id',
            field=models.CharField(blank=True, help_text='Identyfikator w systemie Sejmu', max_length=50, verbose_name='ID w API Sejmu'),
        ),
    ]
