# Generated by Django 4.2.7 on 2025-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_api_data_bill_data_source_bill_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='document_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do dokumentu'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='eli',
            field=models.URLField(blank=True, help_text='European Legislation Identifier', max_length=500, verbose_name='ELI'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do źródła'),
        ),
    ]
