# Generated by Django 4.2.7 on 2025-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_document_url_alter_bill_eli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='project_type',
            field=models.CharField(choices=[('rządowy', 'Rządowy'), ('obywatelski', 'Obywatelski'), ('poselski', 'Poselski'), ('senacki', 'Senacki'), ('unknown', 'Nieznany')], default='unknown', max_length=20, verbose_name='Typ projektu'),
        ),
    ]
