# Generated by Django 4.2.7 on 2025-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='attachments',
            field=models.JSONField(blank=True, help_text='Lista załączników (PDF, DOCX)', null=True, verbose_name='Załączniki'),
        ),
        migrations.AddField(
            model_name='bill',
            name='full_text',
            field=models.TextField(blank=True, help_text='Pełny tekst projektu z załączników', verbose_name='Pełny tekst'),
        ),
    ]
