# Generated by Django 4.2.7 on 2025-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_attachments_bill_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='full_text',
            field=models.TextField(blank=True, help_text='Pełny tekst projektu z załączników', null=True, verbose_name='Pełny tekst'),
        ),
    ]
