# Generated by Django 4.2.7 on 2025-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='attachment_files',
            field=models.JSONField(blank=True, help_text='Przechowywane pliki załączników', null=True, verbose_name='Pliki załączników'),
        ),
    ]
