# Generated by Django 4.2.7 on 2025-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill_attachment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='Analiza projektu przez AI (zmiany, zagrożenia, korzyści)', null=True, verbose_name='Analiza AI'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ai_analysis_date',
            field=models.DateTimeField(blank=True, help_text='Kiedy została wykonana analiza AI', null=True, verbose_name='Data analizy AI'),
        ),
        migrations.AddField(
            model_name='bill',
            name='president_signature_date',
            field=models.DateField(blank=True, help_text='Kiedy Prezydent podpisał projekt', null=True, verbose_name='Data podpisu Prezydenta'),
        ),
        migrations.AddField(
            model_name='bill',
            name='president_signed',
            field=models.BooleanField(default=False, help_text='Czy projekt został podpisany przez Prezydenta', verbose_name='Podpisany przez Prezydenta'),
        ),
        migrations.AddField(
            model_name='bill',
            name='president_veto',
            field=models.BooleanField(default=False, help_text='Czy Prezydent zawetował projekt', verbose_name='Weto Prezydenta'),
        ),
        migrations.AddField(
            model_name='bill',
            name='president_veto_date',
            field=models.DateField(blank=True, help_text='Kiedy Prezydent zawetował projekt', null=True, verbose_name='Data weta Prezydenta'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sejm_votes',
            field=models.JSONField(blank=True, help_text='Dane o głosowaniach posłów nad projektem', null=True, verbose_name='Głosowania w Sejmie'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sejm_votes_date',
            field=models.DateTimeField(blank=True, help_text='Kiedy odbyło się ostatnie głosowanie', null=True, verbose_name='Data ostatniego głosowania'),
        ),
    ]
