# Generated by Django 4.2.7 on 2025-10-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_ai_analysis_bill_ai_analysis_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='president_signature_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='president_signed',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='president_veto',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='president_veto_date',
        ),
    ]
