# Generated by Django 4.2.7 on 2025-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_remove_bill_president_signature_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='sejm_votes',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sejm_votes_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='club_results',
            field=models.JSONField(blank=True, help_text='Wyniki głosowania według klubów', null=True, verbose_name='Wyniki klubów'),
        ),
        migrations.AddField(
            model_name='bill',
            name='druk_numbers',
            field=models.JSONField(blank=True, help_text='Numery druków związane z głosowaniem', null=True, verbose_name='Numery druków'),
        ),
        migrations.AddField(
            model_name='bill',
            name='session_number',
            field=models.CharField(blank=True, help_text='Numer posiedzenia Sejmu', max_length=10, verbose_name='Nr posiedzenia'),
        ),
        migrations.AddField(
            model_name='bill',
            name='voting_date',
            field=models.CharField(blank=True, help_text='Data głosowania w Sejmie', max_length=50, verbose_name='Data głosowania'),
        ),
        migrations.AddField(
            model_name='bill',
            name='voting_number',
            field=models.CharField(blank=True, help_text='Numer głosowania', max_length=10, verbose_name='Nr głosowania'),
        ),
        migrations.AddField(
            model_name='bill',
            name='voting_results',
            field=models.JSONField(blank=True, help_text='Wyniki ogólne głosowania', null=True, verbose_name='Wyniki głosowania'),
        ),
        migrations.AddField(
            model_name='bill',
            name='voting_time',
            field=models.CharField(blank=True, help_text='Godzina głosowania', max_length=20, verbose_name='Godzina głosowania'),
        ),
        migrations.AddField(
            model_name='bill',
            name='voting_topic',
            field=models.TextField(blank=True, help_text='Temat głosowania', verbose_name='Temat głosowania'),
        ),
    ]
