# Generated by Django 4.2.7 on 2025-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_remove_bill_sejm_votes_remove_bill_sejm_votes_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='voting_number',
            field=models.IntegerField(blank=True, help_text='Numer głosowania', null=True, verbose_name='Nr głosowania'),
        ),
    ]
