# Generated by Django 4.2.7 on 2025-10-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_bill_voting_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa klubu')),
                ('color_hex', models.CharField(help_text='Format: #RRGGBB', max_length=7, verbose_name='Kolor (HEX)')),
                ('color_name', models.CharField(blank=True, help_text='Np. Czerwony, Niebieski', max_length=100, verbose_name='Nazwa koloru')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Kolor klubu',
                'verbose_name_plural': 'Kolory klubów',
                'ordering': ['club_name'],
            },
        ),
    ]
