# Generated by Django 4.2.7 on 2025-10-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Zatwierdzony')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Edytowany')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Liczba polubień')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Liczba niepolubień')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Liczba odpowiedzi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bills.bill')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Nieodpowiednia treść'), ('harassment', 'Nękanie'), ('hate_speech', 'Mowa nienawiści'), ('false_information', 'Fałszywe informacje'), ('other', 'Inne')], max_length=20, verbose_name='Powód zgłoszenia')),
                ('description', models.TextField(blank=True, verbose_name='Dodatkowy opis')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Rozwiązane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie komentarza',
                'verbose_name_plural': 'Zgłoszenia komentarzy',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Polubienie (True) / Niepolubienie (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Polubienie komentarza',
                'verbose_name_plural': 'Polubienia komentarzy',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
